default: &default
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

set: &set
  animals:
    <<: *default
    url: <%= URI.parse(ENV['DATABASE_URL_ANIMALS']).tap { |uri| uri.password = ENV['DATABASE_PASSWORD_RW'] }.to_s %>
  animals_replica:
    <<: *default
    url: <%= URI.parse(ENV['DATABASE_URL_ANIMALS_REPLICA']).tap { |uri| uri.password = ENV['DATABASE_PASSWORD_RO'] }.to_s  %>
    replica: true


# https://guides.rubyonrails.org/active_record_multiple_databases.html
development:
  <<: *set

test:
  <<: *set

production:
  <<: *set
