default: &default
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

set: &set
  animals:
    <<: *default
    url: <%= URI.parse(ENV['DATABASE_URL_ANIMALS']) %>
  animals_replica:
    <<: *default
    url: <%= URI.parse(ENV['DATABASE_URL_ANIMALS_REPLICA']) %>
    replica: true


# https://guides.rubyonrails.org/active_record_multiple_databases.html
development:
  <<: *set

test:
  <<: *set

production:
  <<: *set
